name: Build and Deploy Angular App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checar el repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso 2: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Paso 3: Instalar dependencias en el directorio
      - name: Install dependencies
        working-directory: ./gastosub-app
        run: npm install

      # Paso 4: Construir el proyecto Angular
      - name: Build Angular App
        working-directory: ./gastosub-app
        run: npm run build

      # Paso 5: Copiar los archivos a la máquina remota por SCP
      - name: Copy build to remote server
        env:
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PASSWORD: ${{ secrets.REMOTE_PASSWORD }}
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
          echo "Added ${{ secrets.REMOTE_HOST }} to known_hosts."
          sshpass -p "${REMOTE_PASSWORD}" scp -r ./gastosub-app/dist/gastosub-app/browser/* ${REMOTE_USER}@${REMOTE_HOST}:/var/www/html/gastosub-app
